### ISSUE TITLE
Parentheses

### ISSUE THREAD

**Issue by kddnewton** [Shopify/yarp#144]
We don't currently handle parentheses, but we should. For example:

```ruby
1 * (2 + 3)
```

This should continue parsing but lower the binding power down to the beginning and then expect a closing parenthesis.

**Comment by jpcamara** [comment]
Is there more you could expand on about the scope of this particular issue?

Is this generally about precedence with any arbitrary parens anywhere in a file? 

I pulled down the repo and got everything running. I don't have much C experience but I'd be willing to give it a go!

**Comment by kddnewton** [comment]
Fixed by #175
