### ISSUE TITLE
Argument forwarding in method declarations

### ISSUE THREAD

**Issue by kddnewton** [Shopify/yarp#161]
We need to support the `...` operator in our method declarations. This will involve updating our `parse_parameters` function.

**Comment by DRBragg** [comment]
I haven't written much C since High School and I'm pretty sure I was rubbish at it back them so forgive me if I'm not reading this right. Isn't this already handled in `parse_parameters` with `case YP_TOKEN_DOT_DOT_DOT`?

**Comment by kddnewton** [comment]
lol and @DRBragg is the first to close an issue
