### ISSUE TITLE
Design document is editable

### ISSUE THREAD

**Issue by qoops-1** [Shopify/yarp#164]
Hi,
I have opened the Google doc with design description via the [link](https://docs.google.com/document/d/1x74L_paTxS_h8_OtQjDoLVgxZP6Y96WOJ1LdLNb4BKM/edit#) in the README and I have editing rights for it, so I guess it's open for anyone, you might want to limit the editing rights to avoid it getting messed up

**Comment by kddnewton** [comment]
You can comment but not actually edit the doc. If it gets untenable I'll restrict it to viewing but I wanted folks to be able to comment if they have questions.
