### ISSUE TITLE
Parsing a broken argument gets stuck

### ISSUE THREAD

**Issue by mame** [Shopify/yarp#177]
I found that it gets stuck to parse a method call with keyword arguments.

```
$ ruby -Ilib -Itmp/x86_64-linux/stage/lib/yarp/ -ryarp -e 'YARP.parse("foo(k: 1)")'
^C^C^C
```

As far as I read the code, I think yarp does not support keyword arguments yet. That's fine, but I think an inifinite loop is problematic. For example, parsing the following code fragment also causes an infinite loop.

```
YARP.parse("foo(@)") # gets stuck too
```

I believe the following `while (true)` causes this issue, but I am curious how we should fix it.

https://github.com/Shopify/yarp/blob/937b35b71b5844127495ad9d22160ebfd6d2c654/src/yarp.c#L1578

**Comment by kddnewton** [comment]
Thanks @mame! I've fixed the infinite loop now.
