### ISSUE TITLE
Language server

### ISSUE THREAD

**Issue by kddnewton** [Shopify/yarp#201]
Now that we're parsing much more of the Ruby grammar, it would be helpful to have a visual way of testing it out without having to rerun the parser constantly. As such, we should create a language server that uses the Ruby interface of this library to display diagnostics. 

Here is the one from [Syntax Tree](https://github.com/ruby-syntax-tree/syntax_tree/blob/51d24efc9110d7458d78657ceb6cc436815eb0e3/lib/syntax_tree/language_server.rb) that can be used as a base template. A lot of stuff from there can actually be stripped out to make it even simpler.

Once we have the LSP in place, it would be helpful to have a VSCode extension that used it. Again, we can use the one from [Syntax Tree](https://github.com/ruby-syntax-tree/vscode-syntax-tree/blob/e96795ae11b3dd45d78c090fb5d0fb61c7e15f7d/src/extension.ts) as a template. And again, a lot of stuff can be stripped out.

Ideally I'd like to have both of those in this repository to make it easier to test and use while developing. I don't actually imagine that I'm ever going to recommend people install this plugin because there will be other, better, solutions out there once YARP is more complete. But it would certainly make it easier to, for example, ensure that our error messages are readable and in the correct location.

**Comment by bitwise-aiden** [comment]
Going to be looking into this as a part of Hackdays

**Comment by kddnewton** [comment]
Closing as completed
